\chapter{Constructing a control group}\label{ch:randomisation}

\section{A made-up example}\label{sec:beispiel}
Imagine that a new self-learning method for fostering
Danish reading skills in speakers of German has been developed.
You're tasked with finding out if this new method works
better than the old one.

\paragraph{First attempt} 
You find four students of German philology
who want to learn Danish. You ask them to work
autonomously with the new learning method
half an hour a day for three weeks. After three weeks,
you give them an article from a Danish newspaper,
which they are to summarise orally in German.
Two raters judge these summaries at their own discretion
(20-point scale); the mean of the two ratings per
learner counts as their reading comprehension score.
The average group score is 11/20.\\
What can you conclude from this study?

The answer is `pretty much nothing'.
One of several problems with this study is that 
there is no baseline against which to compare the participants'
average result: We don't know whether 11/20 indicates that the
new learning method works better or worse than the old one, or whether
the old and new learning methods are roughly equally effective.
So we need a comparison or \term{control group}
of people that didn't take part in the intervention.

\paragraph{Second attempt}
You convince four law students to also take part in the study.
They're asked to work with the old learning method
half an hour a day for three weeks.
Then they take the same test as the German philology students.
Their group mean is 8/20.\\
What can you conclude from this study?

\clearpage

\section{Critical questions}\label{sec:validitaet}
The second attempt outlined above also falls short on a number of criteria.
There are a couple of critical questions we can ask, and slightly modified
versions of these questions can be asked about studies in general.

\begin{description}
 \item[Internal validity]
 Can the difference in test scores between the two groups
 be ascribed to the difference in learning methods,
 or do alternative explanations for it present themselves?

 \item[External validity]
 Does the finding apply only to the present \term{sample}
 or can it be generalised to a larger \term{population}?
 To what population, exactly?

 \item[Ecological validity]
 To what extent are the findings applicable
 to the world outside of the lab
 (e.g., teaching, policy)?
 This question is especially important for applied research.
 
 \item[Reliability]
  Are the raw data open for interpretation?
 
 \term{Inter-rater reliability}: Would different observers agree on the measurements?
 
 \term{Intra-rater reliability}: Would the \emph{same} observers agree on the measurements if they had to redo them?
 
  \item[Interpretative consensus]
  I use this non-standard term to refer to the possible problem captured
  by the following question:
 Confronted with the same data, would other researchers draw similar conclusions?

 \item[Replicability]
 Can the results of this study be confirmed
 in an independent \term{replication},
 that is, in a new but otherwise similar study?
\end{description}

\mypar[Ecological validity]{Example}
  Neurolinguistic research may show that using a foreign language highlights
  different brain regions in early and late learners.
  This may be interesting to neurolinguists.
  But for language policy, what's probably more relevant is the extent to which
  these groups differ behaviourally on communicatively relevant tasks.
\parend

\mypar[Interpretative consensus]{Example}
A study with considerable internal, external and ecological validity could show
that beginning L2 French learners vastly prefer using a rising intonation 
over other strategies
for formulating questions, but that more seasoned learners show a more balanced
use of the different strategies (subject--verb inversion, \textit{est-ce que}). 
Researchers may agree on these results, 
but are bound to disagree on which implications, 
if any, they ought to have for L2 French teaching. 

Generally, empirical findings obtained in basic research cannot be used
as evidence for nor against some teaching or learning method.
Such evidence must stem from targeted studies comparing teaching or learning
methods.
\parend
\medskip

The labels above aren't important; the questions behind them are.
Further, the questions asked above can rarely be answered in absolute terms.

\mypar{Exercise}
The second attempt outlined on page \pageref{sec:beispiel} is deficient 
in several of these respects. Discuss a few problems.
\parend

\mypar{Remark}
Depending on your goals, some types of validity
may not be as important as others.
For instance, for most studies in psycholinguistics,
university students are recruited as participants,
and their results don't necessarily generalise
to the population at large. But the purpose of these
studies is often to demonstrate that some
experimental manipulation \emph{can} affect
language use and processing, not that
it will affect language use in all language users.
From this perspective, these studies' lack
of external validity isn't too damning \citep{Mook1983}.
\parend

\begin{framed}
 Anticipate and resolve problems
related to lacking validity and reliability
\emph{before} collecting the data. This often
involves making compromises or coming to the
realisation that you can't satisfactorily
answer all your questions in a single study.
Do \emph{not} assume that some statistical method
will solve your problems.
\end{framed}

\mypar{Exercise}
  \citet{DeWilde2020} found that Flemish children already knew
  a decent number of English vocabulary items even before they took their
  first English class.
  Especially English words similar in both form and meaning to their 
  Dutch translations (i.e., cognates) tended to be commonly known among
  these children.
  In their conclusion, the authors write that
  ``[t]he study also suggests that (\dots) teachers do not need to pre-teach
  some cognate words, even for learners at an elementary level'' (pp.~374--375).
  
  \citet{DeWilde2020} didn't empirically investigate the effects of implementing
  this suggestion. But can you think of an undesirable consequence
  of not `pre-teaching' English words with true Dutch cognates
  but still teaching false friends, i.e., English words for which a Dutch
  word with a similar form but a different meaning exists 
  (e.g., \textit{slim}, which means `clever' in Dutch)?
\parend

\section{Increasing internal validity through randomisation}
Of the three types of validity considered, 
internal validity is the most pressing one:
If internal validity is low, external and ecological validity are both
essentially irrelevant.
Hence,
our first priority is to maximise the study's internal validity, that is,
we want to maximise the chances that any association we find in the data
can be ascribed to the factor of interest.
Confounding in particular represents a substantial threat to internal validity:
As we've seen in Chapter \ref{ch:causality}, confounding variables induce
associations between the variables of interest even in the absence of a causal
link between them. Moreover, even if a causal link does exist between the
variables of interest, confounding variables can bias the association
between them: The association may systematically under- or overestimate the
strength of the causal link. Keeping confounding in check is therefore key.

Your first inclination may be to try to ensure that the intervention and
control groups are identical in all respects save for the treatment itself.
That way, any differences in the outcome variable can't be explained by
confounding due to pre-existing differences between the groups.
However, it is practically
impossible to assign a fixed number of participants to two groups in such a
way that these groups are identical in all respects even in the utterly
unrealistic case where all the relevant information is available beforehand.
Clearly, it's entirely impossible to do so when not all of the relevant information
is available beforehand.

The solution is to assign the participants 
to the study's conditions \term{at random}, i.e., to deliberately leave the allocation
up to chance and chance alone. The \textsc{dag}s in Figure \vref{fig:randomisation} show what such
randomisation achieves. When the participants themselves (or their parents,
or their circumstances, etc.) decide or otherwise affect which condition they end up in ($X$),
confounding is a genuine concern (left).
However, when we assign the participants to the conditions at random,
we \emph{know} that there is no systematic link between pre-existing characteristics
($U$) and $X$, let alone a causal one. That is, randomisation prevents any
causal arrows from entering $X$ (right)! The result of this is that the
non-causal path between $X$ and $Y$ (via $U$) is broken and that the $X$-$Y$
relationship is no longer confounded by $U$.
To highlight that the values of $X$ were specified at random,
we use a subscript $_r$.

\mypar{Definition}
Studies in which the participants
are randomly assigned are called \term{true experiments}.
\parend

Random allocation by itself doesn't guarantee that the results of the
experiment can be trusted or interpreted at face value, but it does eliminate
confounding as a threat to the study's internal validity.

\begin{framed}
 Randomise wherever possible -- unless you have a \emph{very} good reason not to!
\end{framed}

\begin{figure}[tbp]
    \centering
    \begin{minipage}{0.45\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figure/w_o_randomisation}
    \end{minipage}\hfill
    \begin{minipage}{0.45\textwidth}
        \centering
        \includegraphics[width=\textwidth]{figure/w_randomisation}
    \end{minipage}
    \caption{\textit{Left:} The $X$-$Y$ relationship is confounded by $U$: there are two paths from $X$ to $Y$, but only one causal one.
    \textit{Right:} Randomising the values of $X$ prevents arrows from $U$ entering $X$, which effectively closes the non-causal path
    via the confounder.}
    \figlabel{fig:randomisation}
\end{figure}

\mypar{Tip}
  When reading empirical research articles, always look up if and how
  the participants (or classes, or whatever is of interest) were assigned
  to the study's conditions.
  And unless it explicitly says that the assignment was carried out at
  random, do not assume that it was.
\parend

\mypar{Exercise}
  Skim the article by \citet{Offerman2016}
  and answer the following questions.
  
  \begin{enumerate}
    \item The study features two \term{conditions}:
    an experimental group and a control group.
    Briefly describe the difference between these conditions in terms
    of what the participants were asked to do. (Sections 3.1 and 3.3.)
    
    \item Consider the first research question on p.~48:
    ``Does a visual feedback paradigm improve production of the segmental
    feature voice onset time?''
    
    Based on your answer to the previous question, complete the following:
    
    ``Does a visual feedback paradigm improve production of the segmental
    feature voice onset time compared to [\textsc{your answer}]?''
    
    What would a stronger baseline for the comparison look like, and why?
    
    \item Who were the participants in this study? 
    Do the authors report how the participants were assigned to the study's
    conditions? (Section 3.1.) 
    How does this affect our (i.e., the readers') ability to judge the study's
    internal validity? \parend
\end{enumerate}

\subsection{Why experiments?}
 \begin{enumerate}
  \item ``Experiments allow us to set up a \textbf{direct comparison} between the treatments of interest.
  \item ``We can design experiments to \textbf{minimize any bias} in the comparison. [especially randomisation]
  \item ``We can design experiments so that the \textbf{error} in the comparison is \textbf{small}. [see later chapters]
  \item ``Most important, we are \textbf{in control} of experiments, and having that control allows us to make stronger inferences about the nature of differences that we see in the experiment. Specifically, we may make \textbf{inferences about causation}.'' \citep[p.~2, my emphasis]{Oehlert2010}
 \end{enumerate}

What's meant by the first point is that we don't need to piece together snippets of evidence
from different and often difficult-to-reconcile sources (e.g., in a literature review) to figure
out which treatment (e.g., which learning method) works best in some situation.
Instead, we set up an experiment that directly evaluates the efficacy of several treatments
in the context we're interested in.

The second point alludes to techniques such as randomisation; the third to techniques
that we will encounter in the chapters to come.

\subsection{What does randomisation do?}
\begin{enumerate}
 \item ``Randomization balances the population on average.''
 \item ``The beauty of randomization is that it helps prevent confounding, \emph{even
for factors that we do not know are important}.'' \citep[p.~15, my emphasis]{Oehlert2010}
\end{enumerate}

We've already discussed the second point, 
but the first point warrants some explanation.
Some fundamental results from combinatorics are useful at this stage.

\mypar{Lemma}\label{lemma:permutations}
  If you have $n \geq 0$ distinct objects,
  there are 
  \begin{align*}
    \begin{cases}
      n(n-1)\cdots 2 \cdot 1, & \textrm{if $n \geq 1$}, \\
      1,                      & \textrm{if $n = 0$},
    \end{cases}
  \end{align*}
  different ways to sort them (`\term{permutations}').
\parend

\begin{proof}\marginnote{This script includes a few proofs. You don't have
to learn them as such (I won't ask for proofs on the exam), but do try to 
understand them. The reason why I included them is that these proofs 
help to demystify what might otherwise seem to be arbitrary pronouncements.
Further, these proofs clarify exactly which assumptions a claim depends on 
and how far it extends: a proof can show you that an argument holds regardless 
of some detail that you might otherwise have assumed was essential to it.}
  If $n = 0$, there is only one way to sort the objects: do nothing.

  If $n \geq 1$: There are $n$ candidates to fill the first slot.
  Once a candidate for the first slot has been picked,
  $n-1$ candidates remain for the second slot, and so on,
  till there is only a single candidate left for the final slot.
\end{proof}

\mypar[Factorial]{Definition}
  For any natural number $n$, we define
  \begin{align*}
    n! :=     
    \begin{cases}
      n(n-1)\cdots 2 \cdot 1, & \textrm{if $n \geq 1$}, \\
      1, &\textrm{if $n = 0$.}
    \end{cases}
  \end{align*}
  We say `$n$ \term{factorial}' for `$n!$'.
\parend

\mypar{Lemma}
	There are
  \begin{align*}
    \frac{n!}{k!(n-k)!}
  \end{align*}
  different ways to choose $k \geq 0$ objects from among $n \geq k$
  distinct objects.
\parend

\begin{proof}
  With Lemma \ref{lemma:permutations}, there are $n!$ ways to arrange the $n \geq 0$ distinct objects.
  For each possible rearrangement, pick the first $k$ objects.
  This covers all possible choices of $k$ from $n$ objects.
  However, several rearrangements result in the same selection.
  Specifically, if we rearrange the first $k$ elements and the last $n-k$
  elements separately from each other, we end up with the same selection:
  the order among the first $k$ and among the last $n-k$ doesn't matter.
  Hence, again with Lemma \ref{lemma:permutations}, there are, for each of the $n!$ permutations,
  $k!(n-k)!$ rearrangements that result in the same selection.
  So there are $\frac{n!}{k!(n-k)!}$ different possible selections.
\end{proof}

\mypar[Binomial coefficient]{Definition}
  For natural numbers $n$ and $k$ with $n \geq k$, we define
  \[
    {n \choose k} := \frac{n!}{k!(n-k)!}.
  \]
  A term of this form is called a
  \term{binomial coefficient};
  we say `$n$ choose $k$' for `${n \choose k}$'.\marginnote{The binomial coefficient is called so because these terms
  appear when expanding binomial expressions such as $(a + b)^n$. 
  In German, one usually says `$n$ tief $k$' or `$k$ aus $n$' for $n \choose k$; 
  in French, `$k$ parmi $n$'.}
\parend
\medskip

<<partiq, fig.width = 2, fig.height = 1.7, include = FALSE, echo = FALSE, results = 'hide', fig.path = 'figure/', dev = 'pdf'>>=
set.seed(2026-06-12)
df <- data.frame(Subject = letters[1:10],
                 IQ = round(rnorm(10, 100, 15)),
                 Sex = sample(c("M", "F"), 10, replace = TRUE))
df$Subject <- factor(df$Subject)
df$Subject <- reorder(df$Subject, df$IQ)
ggplot(df, 
       aes(x = IQ, y = Subject, shape = Sex)) +
  geom_point(size = 2) +
  ylab("") +
  scale_shape_manual(values = c(1, 3)) +
  theme_bw(8) +
  theme(legend.position = "none")
@

\begin{marginfigure}
  \centering
  \includegraphics{figure/partiq-1}
  \caption{Ten participants sign up for a study. You measure their IQ and you also know their sex (represented here using circles and crosses).}
  \figlabel{fig:partiq}
\end{marginfigure}

Let's say that we have ten participants
and we know both their sex and their IQ (Figure \vref{fig:partiq}).
We can pick five among them at random and assign them to the first condition;
the others are assigned to the second condition.
By the previous lemma, there are
\[
  {10 \choose 5} = \frac{10!}{5!(10-5)!} = \frac{3628800}{(120)^2} = 252
\]
different choices for the participants in the first group;
each of these choices has an equal probability of being our allocation.
Six out of the 252 possible allocations are shown in Figure \ref{fig:rand-alloc}.
Note that in none of them, the intervention and control groups are
perfectly balanced with respect to both IQ and sex.
So randomisation clearly does not generate balanced groups in any particular
study. 
However, each participant is as likely to end up in the intervention
group as any other participant, and the same goes for the control group.
So \emph{on average}---across
all 252 possible allocations---sex, IQ, as well as all unmeasured variables,
are balanced between the two groups. For our present purposes, this means that
randomisation is an equaliser: the result may not be two perfectly equal groups,
but at least one group isn't systematically given an advantage relative to the other.
As we'll see in Chapter \ref{ch:stats}, randomisation also justifies the use of some
common statistical procedures.

<<rand-alloc, fig.width = 8*0.85, fig.height = 6*0.85,  include = FALSE, echo = FALSE, results = 'hide', fig.path = 'figure/', dev = 'pdf'>>=
set.seed(2026-06-12)
df$Kondition <- c(rep("control", 5), rep("intervention", 5))

df$Kondition <- sample(df$Kondition)
df <- df %>% group_by(Kondition) %>% mutate(GroupMean = mean(IQ))
p1 <- ggplot(df, aes(x = IQ, y = Subject, shape = Sex)) + geom_point(size = 3) +
  ylab("") +
  facet_wrap(~ Kondition, ncol = 1, scales = "free_y") +
  scale_shape_manual(values = c(1, 3)) +
  geom_vline(aes(xintercept = GroupMean), data = df, linetype = 3) +
  theme(legend.position = "none")

df$Kondition <- sample(df$Kondition)
df <- df %>% group_by(Kondition) %>% mutate(GroupMean = mean(IQ))
p2 <- ggplot(df, aes(x = IQ, y = Subject, shape = Sex)) + geom_point(size = 3) +
  ylab("") +
  facet_wrap(~ Kondition, ncol = 1, scales = "free_y") +
  scale_shape_manual(values = c(1, 3)) +
  geom_vline(aes(xintercept = GroupMean), data = df, linetype = 3) +
  theme(legend.position = "none")

df$Kondition <- sample(df$Kondition)
df <- df %>% group_by(Kondition) %>% mutate(GroupMean = mean(IQ))
p3 <- ggplot(df, aes(x = IQ, y = Subject, shape = Sex)) + geom_point(size = 3) +
  ylab("") +
  facet_wrap(~ Kondition, ncol = 1, scales = "free_y") +
  scale_shape_manual(values = c(1, 3)) +
  geom_vline(aes(xintercept = GroupMean), data = df, linetype = 3) +
  theme(legend.position = "none")

df$Kondition <- sample(df$Kondition)
df <- df %>% group_by(Kondition) %>% mutate(GroupMean = mean(IQ))
p4 <- ggplot(df, aes(x = IQ, y = Subject, shape = Sex)) + geom_point(size = 3) +
  ylab("") +
  facet_wrap(~ Kondition, ncol = 1, scales = "free_y") +
  scale_shape_manual(values = c(1, 3)) +
  geom_vline(aes(xintercept = GroupMean), data = df, linetype = 3) +
  theme(legend.position = "none")

df$Kondition <- sample(df$Kondition)
df <- df %>% group_by(Kondition) %>% mutate(GroupMean = mean(IQ))
p5 <- ggplot(df, aes(x = IQ, y = Subject, shape = Sex)) + geom_point(size = 3) +
  ylab("") +
  facet_wrap(~ Kondition, ncol = 1, scales = "free_y") +
  scale_shape_manual(values = c(1, 3)) +
  geom_vline(aes(xintercept = GroupMean), data = df, linetype = 3) +
  theme(legend.position = "none")

df$Kondition <- sample(df$Kondition)
df <- df %>% group_by(Kondition) %>% mutate(GroupMean = mean(IQ))
p6 <- ggplot(df, aes(x = IQ, y = Subject, shape = Sex)) + geom_point(size = 3) +
  ylab("") +
  facet_wrap(~ Kondition, ncol = 1, scales = "free_y") +
  scale_shape_manual(values = c(1, 3)) +
  geom_vline(aes(xintercept = GroupMean), data = df, linetype = 3) +
  theme(legend.position = "none")

library(gridExtra)
grid.arrange(p1, p2, p3, p4, p5, p6, ncol = 3)
@

\begin{figure}[tpbh]
  \centering
  \includegraphics[max width = \textwidth]{figure/rand-alloc-1}
  \caption{Six possible random assignments (out of 252) of the ten participants from Figure \ref{fig:partiq}. The dotted vertical lines show the mean IQ in each group.}
  \figlabel{fig:rand-alloc}
\end{figure}


\mypar{Exercise}
For each description, decide whether the participants were randomly assigned
to the experiment's conditions and, if not, explain how the lack of randomisation
could result in confounding.

\begin{enumerate}[(a)]
 \item 60 participants trickle into the lab.
 The first 30 are assigned to the experimental condition,
 the final 30 are assigned to the control group.
 
 \item Experiment with a school class:
 Pupils whose last name starts with a letter between
 A and K are assigned to the control group,
 the others to the experimental group.
 
 \item Participants come to the lab one by one.
 For each participant, the researcher throws a dice.
 If the dice comes up 1, 2, or 3, the participant is
 assigned to the experimental condition; if it comes
 up 4, 5, or 6, the participant is assigned to the control
 condition.
 After four weeks, no more participants sign up.
 The control group consists of 17 participants;
 the experimental group of 12.
 
 \item Participants come to the lab one by one.
 The first participant is assigned to the experimental condition,
 the second to the control condition,
 the third to the experimental condition,
 the fourth to the control condition, etc.
 Of the 29 participants who signed up in total, 15 are assigned to the
 experimental condition and 14 to the control condition.
 
 \item To investigate the effects of bilingualism
 on children's cognitive development, 20 bilingual
 4-year-olds (10 girls, 10 boys) are recruited.
 20 monolingual 4-year-olds (10 girls, 10 boys)
 serve as the control group.
 
 \item 32 participants sign up for an experiment.
 The researcher enters their names into \url{http://www.random.org/lists/},
 clicks \texttt{Randomize}, 
 inspects the resulting list,
 and decides to assign
 the first 16 to the control group
 and the others to the experimental group.
 
 \item 32 participants sign up for an experiment.
 The researcher enters their names into \url{http://www.random.org/lists/},
 clicks \texttt{Randomize}, 
 and, without first looking at the resulting list, 
 the first 16 to the control group
 and the others to the experimental group. \parend
\end{enumerate}

\begin{framed}
`Random' does not mean `haphazard', `arbitrary' or `at the researcher's whim'.
\end{framed}

\mypar[Randomisation and estimation]{Remark}\label{remark:estimation}
  When participants are assigned randomly to the experiment's conditions,
  the results of the experiment are also subject to randomness.
  To appreciate this, 
  consider an experiment for which sixteen participants sign up.
  The left-side panel in Figure \ref{fig:estimation} shows the score
  that each participant would have obtained in both conditions
  (often referred to as their \term{potential outcomes} in the literature
  on causal inference; see Definition \vref{def:potentialoutcomes}).
  The difference between both of these scores varies somewhat between
  participants, but on average, it amounts to one point.
  This is the true average intervention (or treatment) effect that is the target
  of the experiment.
  
  Depending on the condition they are assigned to, 
  we would only observe one of the scores for each participant, however.
  If we randomly assign nine of the sixteen participants to the intervention
  condition and seven to the control condition,
  we end up with one out of ${16 \choose 9} = 11,440$ possible allocations.
  To estimate the true average intervention effect,
  we can compute the mean difference between the scores of the participants
  assigned to the intervention condition and those assigned to the control condition.
  The estimated intervention effect would then be one of the 11,440
  values summarised in the histogram on the right-hand side.
  While the \emph{average} estimated intervention effect coincides with
  the true intervention effect (i.e., the estimation is unbiased;
  see Theorem \vref{th:unbiased}),
  depending on the actual allocation, the estimated intervention effect
  may differ considerably from the true one.
  In Chapter \ref{ch:precision}, we'll discuss techniques for increasing the precision
  of the estimation.
\parend

<<estimation, fig.width = 8*0.85, fig.height = 3.5*0.85,  include = FALSE, echo = FALSE, results = 'hide', fig.path = 'figure/', dev = 'pdf'>>=
set.seed(2026-07-18)
n <- 16
untreated <- 10 + 2 * rt(n, 2.1)
treatment_effect <- rpois(n, 3) + rnorm(n, 0.2)
treatment_effect <- treatment_effect - mean(treatment_effect) + 1
treated <- untreated + treatment_effect
selections <- combn(1:n, 9)
M <- ncol(selections)
mean_diffs <- vector(length = M)
for (i in 1:M) {
  mean_diffs[[i]] <- mean(treated[selections[, i]]) - mean(untreated[-selections[, i]])
}
d <- tibble(
  participant = LETTERS[1:n],
  intervention = treated,
  control = untreated
) |> 
  pivot_longer(cols = intervention:control,
               names_to = "Condition",
               values_to = "Outcome")
p1 <- ggplot(d,
       aes(x = Outcome,
           y = reorder(participant, Outcome),
           shape = Condition)) +
  geom_point() +
  scale_shape_manual(values = c(1, 3)) +
  xlab("Outcome") +
  ylab("Participant ID") +
  theme(legend.position = "right")

p2 <- tibble(mean_diffs = mean_diffs) |> 
  ggplot(aes(x = mean_diffs)) +
  geom_histogram(binwidth = 0.25, center = 1, colour = "darkgrey", fill = "lightgrey") +
  geom_vline(xintercept = mean(mean_diffs), linetype = "dashed", colour = "black") +
  scale_x_continuous(breaks = seq(floor(min(mean_diffs)), ceiling(max(mean_diffs)), by = 1)) +
  xlab("Mean difference between conditions") +
  ylab("Frequency")

grid.arrange(p1, p2, ncol = 2)
@

\begin{figure}[tpbh]
  \centering
  \includegraphics[max width = \textwidth]{figure/estimation-1}
  \caption{\textit{Left:} The scores that each of the sixteen participants
  would have obtained if they had been assigned to the control group (circles)
  or to the intervention group (crosses). The average difference between
  the intervention and the control scores, i.e., the average intervention effect, 
  is one point. 
  \textit{Right:} The histogram shows the distribution of the mean difference
  between the intervention and control scores for each of the 11,440
  possible allocations of participants to the two conditions.
  Averaged over all allocations, the mean difference is also one point.
  But for many individual allocations, the mean difference may differ considerably
  from the true average intervention effect of one point.}
  \figlabel{fig:estimation}
\end{figure}

\mypar[Potential outcomes]{Definition}\label{def:potentialoutcomes}
  Consider a study in which $N$ units are each observed in 
  one of $K$ conditions (numbered $0, 1, \dots, K-1$).
  We denote by $Y_i(k)$ the value on the outcome variable 
  that was observed for the $i$-th unit assigned to the $k$-th condition
  or that would have been observed for this unit had it been
  assigned to the $k$-th condition, $i = 1, \dots, N, k = 0, \dots, K-1$.
  These values, which may be unknown, are called \term{potential outcomes}.
\parend

\mypar{Theorem}\label{th:unbiased}
  When using random assignment, 
  the mean difference in the outcome between the control and intervention groups
  averaged over all possible allocations equals the true average (mean) intervention 
  effect.
\parend

\begin{proof}
  Assume an experiment with $m$ units of which $n_1$ are randomly assigned to 
  the intervention
  condition and $n_0 = m - n_1$ are assigned to the control condition;
  i.e., there are $\binom{m}{n_1} = \binom{m}{n_0}$ possible allocations.
  The true average intervention effect is defined as the mean of the
  $m$ per-unit differences between the potential outcomes in the intervention 
  and in the control condition.
  Equivalently, we can compute it as the difference between the mean
  of the $m$ potential outcomes in the intervention condition and the mean
  of the $m$ potential outcomes in the control condition.
  
  The estimate we obtain from any particular random allocation is computed
  as the difference between the mean outcome among the $n_1$ units assigned to
  the intervention condition and the mean outcome among the $n_0$ units assigned
  to the control condition.
  Across all possible allocations, 
  every unit is assigned to the intervention condition equally often;
  this works out to $\frac{n_1}{m} \cdot \binom{m}{n_1} = \binom{m-1}{n_1 - 1}$
  times.
  Similarly, every unit is assigned to the control condition equally often;
  this works out to $\frac{n_0}{m} \cdot \binom{m}{n_0} = \binom{m-1}{n_0 - 1}$
  times.
  
  The mean intervention outcome averaged over all ${m} \choose {n_1}$ allocations
  is therefore the sum of $\binom{m-1}{n_1 - 1}$ times each intervention
  potential outcome divided by $n_1 \cdot \binom{m}{n_1}$.
  You can verify that 
  \[
    \left. \binom{m-1}{n_1 - 1} \middle/  \left(n_1 \cdot \binom{m}{n_1}\right)\right.
    = \frac{1}{m}.
  \]
  So the result is the mean potential intervention outcome over all $m$ units.
  Similarly, the mean control outcome averaged over all $\binom{m}{n_0}$ allocations
  is the mean potential control outcome over all $m$ units.
  Hence, averaged over all $\binom{m}{n_1} = \binom{m}{n_0}$ allocations,
  the mean difference between the groups equals the true average intervention effect.
\end{proof}

\mypar{Remark}
  Theorem \ref{th:unbiased} concerns the \emph{mean} difference and 
  the average (i.e., \emph{mean}) intervention effect.
  The statement doesn't generalise to, say, medians.
  To see this, consider an experiment with three units
  whose potential outcomes in the intervention group are $0, 0, 3$
  and whose potential outcomes in the control group are $0, 0, 0$.
  The median intervention effect for these units is 0.
  However, if we randomly assign one unit to the intervention group
  and two to the control group (three possibilities),
  the average median difference between the two groups is
  $\frac{0 + 0 + 3}{3} = 1 \neq 0$.
  
  This counterexample demonstrates that the proof of Theorem \ref{th:unbiased} 
  cannot be adapted to medians.
  In the proof, we first rewrote the mean of the intervention effects
  as the difference between two means; this doesn't work for the median.
  We also were able to compute the average mean intervention and control outcomes
  as averages over $n_1 \cdot \binom{m}{n_1}$ and $n_0 \cdot \binom{m}{n_0}$
  potential outcomes, respectively.
  This doesn't work for the average median outcome.
\parend

\subsection{How to randomise?}

\paragraph{When collecting data using computers}
Have the computer randomly assign the
participants to the conditions
without your involvement. 
Frameworks for running experiments such as OpenSesame 
(\url{https://osdoc.cogsci.nl/}),
PsychoPy (\url{https://www.psychopy.org/})
or jsPsych (\url{https://www.jspsych.org/}) 
all contain functions for allocating participants randomly.

\paragraph{When the data collection does not take place
at the computer and you know who'll be participating
beforehand}
Randomise the list of participants using \url{https://www.random.org/}.
Assign the first half of the list to the experimental condition
and the second half to the control condition.
If the experiment features $k \geq 3$ conditions,
similarly split up the list into $k$ parts.

This procedure is known as \textbf{complete randomisation}.
It guarantees that the number of experimental units is the same
in each condition (or at most one off if the number of units isn't
divisible by the number of conditions).

\paragraph{When the data collection does not take place
at the computer and you don't know who'll be participating
beforehand}
Randomly assign each participant individually
and with the same probability to a condition as they sign up.
This procedure is known as \textbf{simple randomisation}.
In contrast to complete randomisation, you're not guaranteed to end up
with an equal number of units in each condition. This is usually of little
concern, and in fact, simple randomisation arguably reduces the potential
for the researchers' biases to affect the study's results \citep{Kahan2015}.
Importantly, \textbf{there is nothing wrong with having unequal sample sizes}.\marginnote{See blog entry \href{https://janhove.github.io/posts/2015-11-02-unequal-sample-sized/}{\textit{Causes and consequences of unequal sample sizes}}.}

\begin{framed}
 Humans make for poor randomisation devices.
 Always randomise mechanically (preferably with a computer).
\end{framed}

More complex allocation procedures are possible.
Some of these are common in medical research \citep{Rosenberger2016},\marginnote{Incidentally, medical researchers refer to simple randomisation as `complete randomisation'. It's probably best to just spell out how the randomisation was carried out rather than to rely on short-hand terminology.} 
but they are rarely applied in the social sciences.

\mypar[Complete randomisation with several conditions]{Exercise}
  Consider an experiment with 60 participants who are assigned to
  three conditions using complete randomisation (20 participants per condition).
  How many possible assignments of participants to conditions are there under this scheme?
\parend

\mypar[Simple randomisation]{Exercise}
  Consider an experiment with 40 participants, each of which is assigned
  to one of the conditions using simple randomisation.
  How many possible assignments of participants to conditions are there under this scheme?
  Without computing the value of ${40} \choose {20}$, 
  is the number you've obtained smaller or larger than ${40} \choose {20}$?
\parend

\begin{framed}
The word 'experiment' can be used in a stricter or in a looser sense.
The mere fact that a study is referred to as an 'experiment' does \emph{not}
mean that it's a \textit{true experiment} (control group + randomisation):
the use of the label doesn't automatically imply that confounding has been
taken care of.
Many quantitative studies in our field aren't experiments in the strict sense.
Always look up how the participants were assigned to the conditions!
\end{framed}
