\chapter{Inferential statistics 101}\label{ch:stats}
If you've read a few quantitative research articles,
you've probably encountered $p$-values.
This chapter explains the basic logic
behind $p$-value-based inferential statistics.
It does so by explicitly linking the computation of $p$-values
to the random assignment of participants to conditions
in experimental research. If you have ever taken an introductory
statistics class, chances are $p$-values were explained to you
in a different fashion, presumably by making assumptions about
how the observations in the sample were sampled from a larger
population and by making reference to the Central Limit Theorem.
For the explanation in this chapter, however, we're going to take
a different tack and we will ignore the sampling method and
the larger population.
Instead, we're going to leverage what we know about how the
observations, once collected, were \emph{assigned} to the different
conditions of an experiment. The advantages of this approach
are that it connects the design of a study more explicitly to the analysis of its data
and that it is less math-intensive while permitting one
to illustrate several key concepts about inferential statistics.

The goal of this chapter is for you to \emph{understand conceptually} what
statistical tests attempt to achieve, not for you to be able to use them
yourself. As a matter of personal opinion, statistical tests are overused
\citep{Vanhove2020b}. I think that, in your own research,
your focus should be on describing your data (e.g., by means of
appropriate graphs) rather than running umpteen significance tests.
Analysing data and running statistical tests are not synonymous.

\section{An example: Does alcohol intake affect fluency in a second language?}
\paragraph{Research question} Does moderate alcohol consumption increase 
verbal fluency in a foreign language (L2)?

\paragraph{Method}
Nine students (L1 German, L2 English)\marginnote{Nine participants is obviously a very low number of participants, but it keeps things more tractable here.}
are randomly assigned to either the control (four) or the experimental condition (five);
they don't know which condition they're assigned to.
Participants in the experimental condition drink one pint of ordinary beer;
those in the control condition drink one pint of alcohol-free beer.

Afterwards, they watch a video clip and relate what happens in it in English.
This description is taped,
and two independent raters who don't know which condition the participants were assigned to
count the number of syllables uttered by the participants during the first minute.
The mean of these two counts serves as the verbal fluency/speech rate variable.

<<alcoholresults, fig.width = 3.2, fig.height = 3.5, include = FALSE, echo = FALSE, results = 'hide', fig.path = 'figure/', dev = 'pdf'>>=
d <- data.frame(
  Name = c("Sandra", "Nicole", "Maria", "Yves", "Daniel",
           "Nadja", "Lukas", "Thomas", "Michael"),
  Rate = c(5.6, 4.4, 4.2, 4.1, 3.8,
           4.2, 3.7, 3.4, 3.1),
  Condition = rep(c("with", "without"), times = c(5, 4))
)
ggplot(d,
       aes(x = Rate, y = reorder(Name, Rate))) +
  geom_point() +
  facet_wrap(vars(Condition), scale = "free_y", ncol = 1) +
  labs(
    x = "Speech rate (syllables/s)",
    y = NULL
  )
@


\begin{marginfigure}
\includegraphics[width=\textwidth]{figure/alcoholresults-1}
\caption{Individual results of a randomised experiment.}
\figlabel{fig:alcohol_results}
\end{marginfigure}

\paragraph{Results}
The measured speech rates are shown in Figure \ref{fig:alcohol_results}.
On average (mean), the participants in the \textit{with alcohol} condition
uttered 4.42 syllables/second,
compared to 3.60 syllables/second in the \textit{without alcohol} condition.
That is, the mean difference in favour of the \textit{with alcohol} condition
is 0.82 syllables/second.

<<echo = FALSE, eval = TRUE>>=
mean_diff <- function(variable, treatment_idx) {
  mean(variable[treatment_idx]) - mean(variable[-treatment_idx])
}
observed_diff <- mean_diff(d$Rate, which(d$Condition == "with"))

rerandomisations <- combn(1:nrow(d), 5)
H0_stats <- apply(rerandomisations, 2, mean_diff, variable = d$Rate)
H0_stats <- sort(H0_stats)
@

Table \ref{tab:speechrates} lists the precise values for good measure.
This table introduces the shorthand $Y_i(0)$ to refer 
to the $i$-th participant's speech rate if this participant was assigned
to the \textit{without alcohol} condition 
(e.g., Lukas' speech rate is $Y_7(0) =$ 3.7)
and the shorthand $Y_i(1)$ if the participant was assigned to the
\textit{with alcohol} condition (e.g., Daniel's speech rate is $Y_5(1) =$ 3.8).

\begin{table}
\caption{The measured speech rates (syllables/second) 
in the fictitious alcohol--verbal fluency experiment.}
\centering
\begin{tabular}{@{}rlcc@{}}
\toprule
  $i$ & Participant & Without alcohol ($Y_i(0)$)  & With alcohol ($Y_i(1)$) \\
  \midrule
  1 & Sandra        &                             & 5.6 \\
  2 & Nicole        &                             & 4.4 \\
  3 & Maria         &                             & 4.2 \\
  4 & Yves          &                             & 4.1 \\
  5 & Daniel        &                             & 3.8 \\
  6 & Nadja         & 4.2                         & \\
  7 & Lukas         & 3.7                         & \\
  8 & Thomas        & 3.4                         & \\
  9 & Michael       & 3.1                         & \\
\bottomrule
\end{tabular}
\label{tab:speechrates}
\end{table}

\section{Chance as an alternative explanation}
The design of this fictitious experiment has deftly dealt with
two major threats to internal validity:
confounding has been been neutralised by means of randomisation,
and expectancy effects have been kept in check through blinding.
But there is another threat to internal validity that we need
to reckon with:
While we observed a mean difference between the two conditions
of 0.82 syllables/second in favour of the \textit{with alcohol} condition,
this difference could have come about through \emph{chance}.
We are, then, faced with two types of account for this mean difference:

\begin{itemize}
  \item The result we've obtained is due \emph{only} to chance.
  \item The result we've obtained is due to chance \emph{and} systematic factors.
\end{itemize}

\term{Frequentist inferential statistics} seeks to quantify
how surprising the results are if we assume that only chance is at play.
To do so, it attempts to answer the following key question:
\textbf{How likely is it that a difference at least this large would've come about if chance alone were at play?}

If it's pretty unlikely that chance alone would give rise to 
at least the difference observed,
then this can lead one to revisit the assumption that the results are due
only to chance---perhaps some systematic factors are at play after all.
By tradition, the threshold between `pretty unlikely' and `still too likely',
usually written as $\alpha$, is 5\%,
but there is nothing special about this number.
If the result falls below this 5\% threshold,
the difference is said to be `statistically significant'.
This is just a phrase, however, and arguably a poorly chosen one: statistical `significance' doesn't tell you anything about a
result's practical or theoretical import.

\mypar{Tip}
Avoid using the words `significance' and `significant' in their non-technical 
sense when writing about quantitative research.
\parend

\section{The null hypothesis}
The first type of account, namely that the result obtained is due solely
to chance, is known as the \term{null hypothesis} ($H_0$);
the second as the \term{alternative hypothesis} ($H_A$).

A particularly strong version of the first account is that experimental 
conditions do not differentially affect \emph{any} of nine participants'
speech rates.
This version, which is due to \citet{Fisher1935}, is known as the 
\term{strong} (or \term{sharp}) \term{null hypothesis}.

Let us for a moment assume that this strong $H_0$ is correct.
In this case, the participants' speech rates aren't affected at all by the
condition (\textit{without alcohol} vs \textit{with alcohol}) that they
were assigned to.
For instance, 
Sandra was assigned to the \textit{with alcohol} 
and had a speech rate of $Y_1(1)=$ 5.6.
But under the strong $H_0$, had she been assigned to the \textit{without alcohol}
condition, her speech rate would have been $Y_1(0)=$ 5.6, too.
Similarly, under the strong $H_0$, 
we can use the speech rate that Michael had in the \textit{without alcohol} 
condition ($Y_{9}(0) =$ 3.1) to reconstruct the speech rate that he would
have had in the \textit{with alcohol} condition, namely $Y_{9}(1)=$ 3.1.

The strong null hypothesis allows us to fill out the empty cells
in the results table; see Table \ref{tab:potentialoutcomes}.
The putative results are known as \term{potential outcomes}.

\begin{table}
\caption{The potential outcomes in the fictitious alcohol--verbal fluency experiment 
under the strong null hypothesis}
\centering
\begin{tabular}{@{}rlcc@{}}
\toprule
  $i$ & Participant & Without alcohol ($Y_i(0)$)  & With alcohol ($Y_i(1)$) \\
  \midrule
  1 & Sandra        & 5.6                         & 5.6 \\
  2 & Nicole        & 4.4                         & 4.4 \\
  3 & Maria         & 4.2                         & 4.2 \\
  4 & Yves          & 4.1                         & 4.1 \\
  5 & Daniel        & 3.8                         & 3.8 \\
  6 & Nadja         & 4.2                         & 4.2 \\
  7 & Lukas         & 3.7                         & 3.7 \\
  8 & Thomas        & 3.4                         & 3.4 \\
  9 & Michael       & 3.1                         & 3.1 \\
\bottomrule
\end{tabular}
\label{tab:potentialoutcomes}
\end{table}

Let us consolidate these terms into definitions.

\mypar[Potential outcomes]{Definition}
  Consider a study in which $N$ units are each observed in 
  one of $K$ conditions (numbered $0, 1, \dots, K-1$).
  We denote by $Y_i(k)$ the value on the outcome variable 
  that was observed for the $i$-th unit assigned to the $k$-th condition
  or that would have been observed for this unit had it been
  assigned to the $k$-th condition, $i = 1, \dots, N, k = 0, \dots, K-1$.
  These values, which may be unknown, are called \term{potential outcomes}.
\parend

\mypar[Strong null hypothesis]{Definition}
  Under the \term{strong} (or \term{sharp}) \term{null hypothesis},
  we have $Y_i(0) = Y_i(1) = \dots = Y_i(K-1)$ for $i = 1, \dots, N$.
\parend

<<alcoholresults-alt, fig.width = 3.2, fig.height = 3.5, include = FALSE, echo = FALSE, results = 'hide', fig.path = 'figure/', dev = 'pdf'>>=
d2 <- data.frame(
  Name = c("Michael", "Nicole", "Maria", "Yves", "Daniel",
           "Nadja", "Lukas", "Thomas", "Sandra"),
  Rate = c(3.1, 4.4, 4.2, 4.1, 3.8,
           4.2, 3.7, 3.4, 5.6),
  Condition = rep(c("with", "without"), times = c(5, 4))
)
ggplot(d2,
       aes(x = Rate, y = reorder(Name, Rate))) +
  geom_point() +
  facet_wrap(vars(Condition), scale = "free_y", ncol = 1) +
  labs(
    x = "Speech rate (syllables/s)",
    y = NULL
  )
@


\begin{marginfigure}
\includegraphics[width=\textwidth]{figure/alcoholresults-alt-1}
\caption{If only chance were at play, Michael's (3.1) and Sandra's (5.6) results would be unaffected by the experimental condition and the outcome might equally well have looked like this (swapping Michael and Sandra).}
\figlabel{fig:alcohol_results_alt}
\end{marginfigure}

Under the strong $H_0$, we have $Y_i(0) = Y_i(1)$ for $i = 1, \dots, 10$.
The difference between the means of the $Y_i(0)$ and of the $Y_i(1)$ values,
then, is zero.
Still assuming that the strong $H_0$ is correct, then, 
the difference in speech rate between the two conditions that we actually observed
must be due solely to the random assignment of
participants to conditions, due to which more fluent talkers ended up in the 
\textit{with alcohol} condition.
For instance, 
another roll of the dice could have assigned Sandra
to the control condition instead of Michael,
and under the strong null hypothesis, 
this would have produced a slower mean speech rate in the \textit{with alcohol} 
condition than in the
\textit{without alcohol} one 
(3.9 vs. 4.2; see Figure \ref{fig:alcohol_results_alt}).

\section{Testing the null hypothesis by exhausitive rerandomisation}
With 9 participants split up in a control group of 4 and an experimental group of 5
there were ${9 \choose 5} = 126$ possible assignments of participants to conditions,
each of which was equally likely to occur.
To see how easily a difference as least as large as the one observed 
(a mean difference in speech rate of 0.82 in favour of the \textit{with alcohol} condition) 
could occur due to random assignment alone,
we can re-arrange the participants' speech rates into each of these 126 combinations and see for each combination what the difference between the \textit{with} and
\textit{without alcohol} condition means is (Figure \ref{fig:alcohol_test}).

<<randomisationtest, fig.width = 4*0.7, fig.height = 7*0.7, include = FALSE, echo = FALSE, results = 'hide', fig.path = 'figure/', dev = 'pdf'>>=
data.frame(
  diff = H0_stats,
  idx = 1:126
) |> 
  ggplot(aes(x = H0_stats, y = idx)) +
  geom_point(shape = 1, size = 0.5) +
  geom_vline(xintercept = observed_diff, linetype = "dashed", colour = "red") +
  xlab(expression(paste("Mean difference under strong ", H[0]))) +
  ylab("Re-randomisation")
@

\begin{marginfigure}
\includegraphics[width=\textwidth]{figure/randomisationtest-1}
\caption{There are 126 different ways in which the 9 participants could have been split up into two groups
so that there are five participants in the experimental group. These are the differences between the means for all 126 possibilities under the strong null hypothesis.
The mean difference we actually observed (0.82) is represented by the dashed red vertical line.}
\figlabel{fig:alcohol_test}
\end{marginfigure}

In five out of 126 cases, the re-arrangement of participants to conditions
produces a mean difference in speech rate in favour of the \textit{with alcohol}
group that is a least as large as the one we actually observed (0.82).
In other words, under the strong null hypothesis,
the probability with which we would observe a mean difference of at least $0.82$ 
in favour of the \textit{with alcohol} condition if chance alone (in the form
of random assignment) were at play is $\frac{5}{126} \approx$ 0.0397 (3.97\%).
This quantity is known as the \term{p-value}.
The procedure outlined in this section to obtain such $p$-values
is called \term{randomisation testing}.

Using the threshold $\alpha =$ 0.05,
we would find that $p = $ 0.0397 $< \alpha$ and conclude
that a difference of 0.82 or more in favour of the \textit{with alcohol} condition
is fairly unlikely to occur under the strong null hypothesis.
This would provide some evidence that there are systematic factors at play
in producing the mean difference of 0.82.
Since the study's design was specifically intended to minimise major threats to 
internal validity, it could then plausibly be argued
that moderate alcohol consumption increases verbal fluency 
in the L2 in these participants.

\mypar[Directional and non-directional tests]{Remark}\label{rem:directional}
  In the example above, 
  the research question was if moderate alcohol consumption \emph{increases}
  L2 verbal fluency.
  This is a \term{directional} research question,
  and the statistic that we used to compare the groups reflects the direction
  of this research question:
  we computed the mean difference in speech rate between the two conditions
  in favour of the \textit{with alcohol} group.
  
  How would we have proceeded if the research question had been if 
  moderate alcohol consumption \emph{decreases} L2 verbal fluency?
  In this case, we could have computed the mean difference in speech
  rate between the two conditions but this time in favour of the
  \textit{without alcohol} group.
  Proceeding entirely analogously, we would have found that, under the
  strong null hypothesis, 123 out of 126 of the mean differences
  would have been larger than the actually observed mean difference of
  $-0.82$ ($p = \frac{123}{126} \approx 0.98$).
  This would have given us no evidence for an alcohol-induced decrease
  in L2 verbal fluency.
  
  If we hadn't committed to a specific direction, the research question
  should have been formulated in a \term{non-directional} manner:
  Does moderate alcohol consumption \emph{influence} (or affect, change, etc.)
  L2 verbal fluency?
  One suitable statistic to compute in this case would have been
  the \emph{absolute} mean difference between the conditions.
  The analysis would then have shown that, under the strong null hypothesis,
  we would have obtained an absolute mean difference as least as large
  as the one actually obtained (namely 0.82) in 9 out of 126 cases
  ($p = \frac{9}{126} \approx 0.071$).
  Using the threshold $\alpha =$ 0.05, we would then have surmised that
  the study's results are fairly compatible with the strong null hypothesis.
  
  The choice of the statistic chosen to compare the conditions in a
  statistical test, then, affects the outcome of this test.
  Moreover, as we will see in more detail in a moment, it is imperative
  that the choice of this statistic is settled in advance, i.e.,
  before analysing the data.
\parend

\mypar[Other test statistics]{Exercise}
  In your own words, 
  outline how you can compute a $p$-value for the difference 
  between the condition medians in the example above.
  Assume that the research question still is if moderate alcohol intake
  increases L2 verbal fluency.
\parend

\mypar[More than two conditions]{Exercise}
  Let's say we want to conduct an experiment with
  twelve participants who are randomly allocated to
  three conditions with four participants each.
  (Again, the numbers are kept low to keep exhaustive
  rerandomisation feasible.)
  With three conditions, we could compute the 
  three pairwise differences between the condition means.
  But if we want to capture the differences between
  these in a single number, we could instead compute,
  for instance, the standard deviation of the condition means
  (see Exercise \vref{ex:johnson}).
  Standard deviations can't be negative.
  Under $H_0$, you'd expect the condition means to be close to one another,
  so this standard deviation would be close to $0$; 
  under $H_A$, you'd expect it to be higher.
  \begin{enumerate}[(a)]
    \item How many possible ways are there to split up 
    twelve participants into three groups of four participants each?
    \item Explain how you can compute an appropriate $p$-value using
    exhausitive rerandomisation in this setting.
    \item Now assume that we're interested in the group medians rather 
    than in the group means. 
    What would you need to change in your answer to (b)?\parend
  \end{enumerate}
  
\mypar[One-sided and two-sided tests]{*Remark}
  The content of Remark \ref{rem:directional} is more typically phrased
  in terms of one-sided and two-sided tests
  and the resulting left-, right-, and two-sided $p$-values.
  In the present example, we first computed a right-sided test:
  in Figure \ref{fig:alcohol_test}, we counted the number of 
  rerandomisations in which the mean difference was equal to
  or lay to the right of the mean difference that we actually observed.
  Denote the resulting $p$-value by $p_r$.
  
  To compute the left-sided $p$-value, we would have computed
  the number of rerandomisations in which the mean difference was equal to
  or lay to the left of the mean difference that we actually observed.
  The result would have been a $p$-value of $p = \frac{123}{126} \approx 0.98$,
  exactly as we obtained when changing the direction of the mean difference
  in Remark \ref{rem:directional}.
  Denote the left-sided $p$-value by $p_{\ell}$.
  
  A two-sided $p$-value $p_t$ could have been computed by using the absolute 
  mean difference, as in Remark \ref{rem:directional}.
  A slightly better alternative is to compute it as
  \[
    p_t := \min(2 \cdot \min(p_{\ell}, p_r), 1).
  \]
  In `nice' cases, both calculations yield the
  same result. But this isn't true in general.
  This second way of obtaining a two-sided $p$-value 
  seems a bit odd at first blush,
  and its slight advantage over the first method isn't worth
  the confusion it tends to instill in students in an introductory course
  such as this.
\parend
  
\section{On `rejecting' null hypotheses}
Researchers will often say that they `reject' the null hypothesis in
favour of the alternative hypothesis if $p \leq \alpha$, where typically $\alpha = 0.05$.
This practice is subject to often heated debate \citep[see][]{McShane2017},
and it's important to realise that $p \leq \alpha$ is possible
even if the null hypothesis is true.
In theory, 
significance tests guarantee that 
$p \leq \alpha$ in at most 
$100\alpha$\% of the studies in which 
$H_0$ actually is true (for all $\alpha \in (0, 1)$).
This is true in particular for $p$-values 
computed using exhaustive rerandomisation under the strong null hypothesis.

\mypar{Lemma}\label{lemma:boundpval}
  Under the strong null hypothesis, 
  exhaustive rerandomisation results in a $p$-value $P$
  such that $\mathbb{P}(P \leq \alpha) \leq \alpha$ for each $\alpha \in (0, 1)$.
\parend

\begin{proof}
  Assume there are $M$ possible randomisations.
  Under the strong null hypothesis, we can compute the test statistic 
  (e.g., a signed or absolute mean difference in our example)
  for each rerandomisation.
  Sort these test statistics in descending order,
  breaking ties randomly if necessary:
  \[
    t_{1} \geq t_{2} \geq \dots \geq t_{M-1} \geq t_{M}.
  \]
  After this sorting, the $p$-value that the $i$-th randomisation would
  have resulted in (call it $p_i$) is at least $i/M, i = 1, \dots, M$:
  we have $t_1 \geq t_2 \geq \dots \geq t_i$ for each $i$.
  (It is possible that $p_i > i/M$ if $t_{i+1} = t_{i}$.)
  
  For any $\alpha \in (0, 1)$, now compute $\kappa := \lfloor \alpha M \rfloor$.
  ($\lfloor \cdot \rfloor$ rounds down the number to the nearest integer.)
  We were equally likely to have generated
  each of the $M$ possible randomisations.\marginnote{It is possible to generalise
  the procedure for computing $p$-values to cases in which the randomisations
  aren't all equally likely to occur, and the proof of this lemma can be adapted
  to take this into account. I see little value in considering such cases in the present course, however.}
  Hence, the probability that we generated a randomisation resulting
  in a $p$-value $P$ no larger than $\alpha$ is
  \begin{align*}
    \mathbb{P}(P \leq \alpha)
    &= \frac{\textrm{\# randomisations with $p_i \leq \alpha$}}{M}\\
    &\leq \frac{\textrm{\# randomisations with $i/M \leq \alpha$}}{M}\\
    &= \frac{\textrm{\# rerandomisations with $i \leq \kappa$}}{M} \\
    &= \frac{\kappa}{M} \\
    &\leq \alpha.
  \end{align*}
\end{proof}

\mypar{Remark}
  Nothing in the proof of Lemma \ref{lemma:boundpval} depends on the choice
  of test statistic. In the running example, we used the mean difference between
  the conditions as the test statistic. 
  But the difference between the condition median or the probability of superiority
  (see Definition \vref{def:probsup}), or indeed any other statistic,
  can be used instead to obtain a valid $p$-value.
  But what you shouldn't do is try out several approaches and then picking
  the one that `works best'!
\parend

In principle, then, $p$-values can be used to bound the probability 
that we claim that something is going on in the data if in fact nothing is going on:
We pick some value for $\alpha$ (typically 0.05).
If $H_0$ is in fact true, then we'd only observe $p$-values lower than
$\alpha$ with a probability of at most $\alpha$.
In practice, however, things aren't so simple.
We'll return to this when discussing questionable research practices;
but already see Exercise \ref{ex:multipletesting} 
and Example \ref{ex:flexibletesting}.

Furthermore, $p>\alpha$ can occur even
if the alternative hypothesis is true.
Consequently,
researchers who are in the business of `rejecting' null hypotheses
can make two types of errors, depending on whether $H_0$ or $H_A$ is actually true;
see Table \ref{tab:errors}.
Without additional information (e.g., in the form of converging evidence
from other studies or logical reasoning), we can't really know whether
`$p \leq 0.05$' represents an error or a true finding. \textbf{(!)}

\begin{table}[h]
\caption{If you're in the business of rejecting null hypotheses, there are two types of errors you can make.
Incorrectly rejecting the $H_0$ is commonly referred to as a \textbf{Type-I error};
incorrectly not rejecting the $H_0$ is referred to as a \textbf{Type-II error}.}
\centering
\begin{tabular}{@{}lll@{}}
\toprule
                            & $H_0$ is actually correct       & $H_A$ is actually correct \\ \midrule
$p > \alpha$                  & Fine---we didn't reject $H_0$   & Wrong conclusion  \\
$p \leq \alpha$               & Wrong conclusion                & Fine---we rejected $H_0$ \\
\bottomrule
\end{tabular}
\label{tab:errors}
\end{table}

Furthermore, that the $H_A$ stipulates that the results are
due to a combination of chance and systematic factors.
It doesn't stipulate \emph{which} systematic factors, though.
What we would like to conclude is that the systematic factor
at play is our experimental manipulation.
But expectancy effects, failed manipulations, confounding and collider bias
are also systematic factors.

What is more, the experimental manipulation may exert a systematic
effect on the results, but for different reasons from what we think it does.
For instance, a systematic difference between the
\textit{with} and \textit{without alcohol} conditions needn't be due to alcohol intake per se but
may be related to the taste of the beers in question instead.
Or maybe alcohol increases speech rate---not because the participants
become more fluent per se, but because they use simpler syntactic
constructions that they can produce more quickly.
In other studies, different theoretical explanations 
may account for any given finding---in addition to more mundane reasons such as confounding, expectancy effects and the like.

\mypar{Exercise}
Assume that 10,000 experiments are carried out and analysed appropriately.
Further assume that the null hypothesis is correct in all of these experiments.
\begin{enumerate}[(a)]
  \item Which of the four histograms shown in Figure \vref{fig:distr_pvalues}
could plausibly represent the distribution of the 10,000 $p$-values? 
  \item Which of the four histograms would you hope to find if the alternative hypothesis were correct in all of the 10,000 experiments? Why? \parend
\end{enumerate}

\begin{figure*}[htp]
    \centering
    \includegraphics[width=\textwidth]{figure/distr_pvalues}
    \caption{What could the distribution of 10,000 $p$-values look like under the null hypothesis?}
    \figlabel{fig:distr_pvalues}
\end{figure*}

\mypar[False discovery rate]{Exercise}
  Imagine that in a given academic field, 
  1,000 experiments are conducted over the course of a year.
  Assume that in 80\% of these experiments, the null hypothesis is correct,
  whereas in 20\%, the alternative hypothesis is correct.
  Further assume that if the null hypothesis is correct, 
  there is a 5\% chance that a statistically significant difference 
  will be observed between the experiment's conditions; 
  if the alternative hypothesis is correct, 
  there is a 60\% chance of observing a statistically significant difference.

  For the following questions, you may use the following probabilistic fact:
  If $n$ attempts each succeed with probability $p$,
  then the expected number of successful attempts out of the $n$ attempts is $np$.
  
  \begin{enumerate}[(a)]
    \item In how many of the 1,000 experiments can we expect that the
          null hypothesis will be incorrectly rejected?
    \item In how many of the 1,000 experiments can we expect that the
          null hypothesis will be correctly rejected?
    \item Now consider the total number of experiments in which we expect
          to reject the null hypothesis.
          In what percentage of these will the 
          null hypothesis actually be correct?\parend
  \end{enumerate}
        
\mypar[Multiple testing]{Exercise}\label{ex:multipletesting}
A research team is conducting an experiment in 30 school classes
        simultaneously. In each school class, the children are assigned
        to the control or experimental group using complete randomisation.
        That is, the researchers are in effect conducting 30 parallel and
        independent experiments.

        Assume that in all of these classes, the null hypothesis is true.
        Further assume that, if the null hypothesis is true, there is
        exactly a 5\% chance of observing a statistically significant difference between
        the control and experimental conditions.

        What is the probability of obtaining a statistically significant
        difference in at least one of the 30 experiments?
\parend

\mypar[`Flexible' testing]{Example}\label{ex:flexibletesting}
  Lemma \ref{lemma:boundpval} assumes that the analyst decided 
  on a suitable test statistic \emph{before} looking at the data.
  To appreciate this, assume that the strong null hypothesis holds 
  in our running example, that is, that the participants would have had
  the speech rates listed in Table \ref{tab:potentialoutcomes}.
  
  If the analyst decided beforehand to test if moderate alcohol intake
  increases the speech rates and correspondingly used the mean difference
  in favour of the \textit{with alcohol} group as the test statistic,
  then she would have obtained a $p$-value no larger than $\alpha =$ 0.05
  with 4.76\% probability.
  
  Similarly, if she had decided beforehand to test if moderate alcohol intake
  decreases the speech rates and had correspondingly used the mean difference
  in favour of the \textit{without alcohol} condition as the test statistic,
  the she would have obtained a $p$-value no larger than $\alpha =$ 0.05
  with 3.97\% probability.
  In both cases, $\mathbb{P}(P \leq 0.05) \leq 0.05$ as guaranteed by 
  Lemma \ref{lemma:boundpval}.
  
  However, imagine that the analyst had first looked at the data to see
  which condition had the faster average speech rate before deciding
  whether to test whether moderate alcohol intake increased or decreased verbal
  fluency.
  In this case, the probability of obtain a $p$-value no larger than $\alpha =$ 0.05
  would have been 8.73\%---larger than the 5\% upper bound guaranteed by
  Lemma \ref{lemma:boundpval}.
  
  As we will see in Chapter \ref{ch:qrp}, undisclosed flexibility when
  running significance test can render their results essentially meaningless.
\parend

\section{Monte Carlo rerandomisation p-values}
Exhausitive rerandomisation is computationally impossible for larger samples\marginnote{How many ways 
are there to split up 40 participants into two equal-sized groups?
Assuming it takes 3 milliseconds to evaluate one rerandomisation,
how many \emph{years} would it take to run the test when using exhausitive rerandomisation?} 
and may be infeasible for more complex research designs.
One alternative is to use a Monte Carlo simulation:
Instead of generating all possible rerandomisations, 
we only generate, say, 20,000 of them, including the randomisation we actually observed.
Then, we compute the proportion of the rerandomisations considered that resulted
in test statistic values at least as extreme as the one we actually observed;
this proportion serves as the Monte Carlo $p$-value.
The guarantee encapsulated in Lemma \ref{lemma:boundpval} also holds for
such Monte Carlo $p$-values.
However, if you run the same analysis multiple times, 
the resulting $p$-value is bound to vary somewhat from run to run 
due to the inherent randomness in the simulation.

\section{Analytical shortcuts}
Statistical inference predates computers, and analytical shortcuts were developed
to circumvent the tedious computations required for randomisation tests.
These shortcuts include the $t$-test, the $\chi^2$-test, and \textsc{anova}, 
as well as their generalisations.
They typically produce similar results to those produced by randomisation tests
and are usually used instead.
In the context of experiments with random assignment,
the $p$-values that these procedures return have
the essentially same interpretation and are subject to the same caveats as those above.
That said, they are based on a different set of assumptions from randomisation tests.
Typically,
the guarantee from Lemma \ref{lemma:boundpval} only holds approximately
when using these shortcuts
(i.e., $\mathbb{P}(p \leq \alpha) \approx \alpha$ under $H_0$).

\section{Statistical power}\label{sec:power}
A study's statistical power is the probability with which its significance test
will yield $p \leq \alpha$ under the alternative hypothesis, 
for some predetermined $\alpha \in (0, 1)$. 
In studies in which one group is compared to a different
group, this probability depends on three factors apart from $\alpha$ itself 
(see Figure \ref{fig:power}):

\begin{enumerate}
\item The size of the difference in the outcome between the groups
that the systematic factors cause. Even if they don't cause any difference, it is possible to obtain a statistically significant difference due to chance.
\item The number of observations.
\item The variability in the outcome variable within each group.
\end{enumerate}

\begin{figure}
    \centering
    \includegraphics[width=\textwidth]{figure/power}
    \caption{These three graphs show how the statistical power of a study varies with the effect size (left), the number of observations per group (middle) and the variability in the outcome variable within each group (right).}
    \figlabel{fig:power}
\end{figure}

The precise numbers along the $y$-axis in Figure \ref{fig:power}
aren't important; what's relevant is the direction and the shape of the curves.

\mypar{Exercise}
Take a look at Figure \ref{fig:power} and answer the following questions:

\begin{enumerate}[(a)]
\item How do the effect size, the number of observations and the within-group variability in the outcome affect the probability that a study will yield a statistically significant result?

\item Other things equal, what yields a greater improvement in a study's power:
10 additional participants per group when each group already consists of 10 participants, or 20 additional
participants per group, when each group already consists of 50 participants?

\item How could researchers reduce the within-group variability in the outcome variable in order
to increase their statistical power? \parend
\end{enumerate}

\mypar{Exercise}
In an experiment that was carried out and analysed rigorously, we find that the mean difference between the control and intervention groups amounts to 5 points on a 100-point scale. This difference is ``statistically significant'', with a $p$-value of 0.02.

Decide for each claim below whether it follows logically from the description
above.
Briefly explain your reasoning.

\begin{enumerate}[(a)]
  \item It's unlikely that we would have found a difference of 5 points or larger between both groups if the null hypothesis were indeed true. More precisely, this probability would have only been 2\%.

  \item The null hypothesis is incorrect; the alternative hypothesis is correct.

   \item It's unlikely that the null hypothesis is indeed correct. More precisely, the probability that it is correct is only 2\%.

  \item It's highly likely that the alternative hypothesis is correct. More precisely, the probability that it is correct is 98\%.

  \item A new but similar study would likely yield a low $p$-value as well.
  More precisely, there is a 98\% probability that such a study would yield
  a significant $p$-value (i.e., $p \leq 0.05$).

  \item If we concluded that the alternative hypothesis is correct, we would be wrong at most 2\% of the time.

  \item If we concluded that the alternative hypothesis is correct, we would be wrong at most 5\% of the time. \parend
\end{enumerate}

\section{*Examples in R}
See the file \texttt{randomisation\_tests.html}
in the \texttt{tutorials} directory on \url{https://github.com/janhove/QuantitativeMethodology}.

\section{*Further reading}
The blog post 
\href{https://janhove.github.io/posts/2025-11-09-population-randomisation/}{\textit{The population model and the randomisation model of statistical inference}}
discusses why the randomisation-based approach to statistical inference
used in this chapter differs from the population-based approach that is
more commonly taught in introductory statistics courses.
The blog entries 
\href{https://janhove.github.io/posts/2015-02-26-explaining-key-concepts-using-permutation-tests/}{\textit{Explaining key concepts using permutation tests}}
and 
\href{https://janhove.github.io/posts/2014-09-12-a-graphical-explanation-of-p-values/}{\textit{A purely graphical explanation of $p$-values}} 
may be of some further use.

\citet{Goodman2008} discusses some common misinterpretations of $p$-values;
his list is far from exhaustive.

Analysing quantitative data and running significance tests aren't
synonymous; see my booklet as well as \citet{Winter2019} for introductions
to statistics for linguists that don't emphasise signficance testing.
Nonetheless, quantitative research in the social sciences, including in applied
linguistics, has developed something of a significance fetish,
with authors inundating their readers with significance tests and $p$-values
that they themselves don't seem to really understand while giving them
little insight into what the data actually look like.
For further lamentations and some
suggestions, see \citet{Vanhove2020b}.
